---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-devops
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/sysops
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-devops
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-devops
  labels:
    app: pod-devops
spec:
  volumes:
    - name: storage-devops
      persistentVolumeClaim:
        claimName: pvc-devops
  containers:
    - name: container-devops
      image: ngnix:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: storage-devops
          mountPath: /usr/share/nginx/html
---
apiVersion: v1
kind: Service
metadata:
  name: web-devops
spec:
  selector:
    app: pod-devops
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30008
      protocol: TCP
