---
apiVersion: v1
kind: Namespace
metadata:
  name: fieldref-namespace
---
apiVersion: v1
kind: Pod
metadata:
  name: envars
  namespace: fieldref-namespace
  labels:
    name: myapp-envars
spec:
  restartPolicy: Never
  containers:
    - name: fieldref-container
      image: nginx:latest
      command: ["sh", "-c"]
      args:
        - while true; do
          echo -en '/n';
          printenv NODE_NAME POD_NAME;
          printenv POD_IP POD_SERVICE_ACCOUNT;
          sleep 10;
          done;
      env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
