---
apiVersion: v1
kind: Namespace
metadata:
  name: tomcat-namespace-datacenter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment-datacenter
  namespace: tomcat-namespace-datacenter
  labels:
    app: tomcat-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat-server
  template:
    metadata:
      labels:
        app: tomcat-server
    spec:
      containers:
        - name: tomcat-container-datacenter
          image: gcr.io/kodekloud/centos-ssh-enabled:tomcat
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service-datacenter
  namespace: tomcat-namespace-datacenter
spec:
  selector:
    app: tomcat-server
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32227
  type: NodePort
